services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aoe\Cachemgm\:
    resource: '../Classes/*'

  Aoe\Cachemgm\Controller\BackendModuleController:
    public: true

  Aoe\Cachemgm\EventListener\AvoidCacheLoading:
    tags:
      - name: event.listener
        identifier: 'aoepoeple-cachemgm/avoid-cache-loading'
        event: TYPO3\CMS\Frontend\Event\ShouldUseCachedPageDataIfAvailableEvent